### PR TITLE
New executionContext implementation

### PR DESCRIPTION
**Pull request by teams2ua**
Based on java thread pool.
This fix segfault.
Don't know the real reason, but hipothesis is that application crash when it creates too many threads.

### CODE REVIEW

**Comment by gre** [comment]
```
> Task :react-native-ledger-core:compileReleaseJavaWithJavac FAILED
/Users/grenaudeau/dev/ledger-live-mobile/node_modules/@ledgerhq/react-native-ledger-core/android/src/main/java/com/ledger/reactnative/RCTCoreExecutionContext.java:55: error: constructor ExecutionContextImpl in class ExecutionContextImpl cannot be applied to given types;
        ExecutionContextImpl newInstance = new ExecutionContextImpl(this.reactContext);
                                           ^
  required: ReactApplicationContext,int
  found: ReactApplicationContext
  reason: actual and formal argument lists differ in length
1 error
```

**Review by gre — CHANGES_REQUESTED** [review]
see comment above. Java don't compile.

**Comment by gre** [comment]
i've locally fixed the Java (but i'm not sure what number was supposed to be put, i set 1 but maybe it prevent parallel sync?) and the account seems to sync correctly! good job! waiting a fix to come before we merge it

**Comment by hadronized** [comment]
I think that number should be set to the maximum number of cores the target platform support.

```java
int cores = Runtime.getRuntime().availableProcessors();
```

**Comment by teams2ua** [comment]
> I think that number should be set to the maximum number of cores the target platform support.
> 
> ```java
> int cores = Runtime.getRuntime().availableProcessors();
> ```

This code could only be executed before calling one methods in API
```
EventPublisher.newInstance( new execution context here , ...);
```
And it is used for executing one callback, I doubt it needs more then one thread.
Other point is that it is actually never used, look at mobille code at syncAccount.js
```
    const serialContext = await core.coreThreadDispatcher.getMainExecutionContext(
      core.getThreadDispatcher(),
    );

    await core.coreEventBus.subscribe(eventBus, serialContext, eventReceiver);
```
We don't construct new context, we borrow it from ThreadDispatcher, and this is good.
This code was generated by djinni that didn't know this details about the code.

**Review by gre — APPROVED** [review]

**Pull request merged**
