### PR TITLE
Bump version 0.5.0.

### PR DESCRIPTION
**Pull request by hadronized**
This will use lib-core 2.6.0.

### CODE REVIEW

**Comment by hadronized** [comment]
Draft until I have completely tested it on Live Mobile (android, iOS is already ok).

**Review by teams2ua — APPROVED** [review]

**Review by hadronized — COMMENTED** [review]
Those changes include RC / `develop` stuff (XRP). I need to pinpoint to a specific libcore commit and redo it. Fuck.

**Comment by hadronized** [comment]
> Those changes include RC / `develop` stuff (XRP). I need to pinpoint to a specific libcore commit and redo it. Fuck.

Nevermind, let’s go on 2.7.0-rc, actually.

**Comment by hadronized** [comment]
I’ll update  one and final time `develop` for a RC release of `2.7.0`.

**Comment by hadronized** [comment]
Well, nevermind this PR, it’s too messy. Closing. I’ll open another one, sanitized.

**Pull request closed without merging**
